### ISSUE TITLE
Plugin requires Feat. Artists in Titles plugin to be enabled

### ISSUE THREAD

**Issue by MarcusGHub** [fdemmer/Picard-Last.fm.ng-Plugin#3]
The plugin only provides genre and other tags when I enable Feat. Artists in Titles plugin.
If I disable Feat. Artists in Titles and enable Feat. Artists Removed plugin, I get 'Unknown'. Same thing happen if I have only your plugin enabled.

In addition to what I said above, regardless of which plugin I enable along with your plugin, I only get info for tracks without featured artists.

So, if I have a track with just one artist I don't encounter the problem. If I have a track with multiple artists, for example Major Lazer's Powerful, and I have Feat. Artists Removed enabled I get 'Unknown' for genre and other tags. However, if I have Feat. Artists in Titles enabled instead of the Feat. Artists Removed everything works fine.

Only Last.fm.ng ticked
http://prntscr.com/8nby7p

Last.fm.ng and Feat. Artists Removed ticked
http://prntscr.com/8nbzdw

Last.fm.ng and Feat. Artists in Titles ticked
http://prntscr.com/8nc0at

Am I doing something wrong?

**Comment by fdemmer** [comment]
no, you aren't doing anything wrong, but the plugin is also not doing anything wrong :)
- the 'Feat. Artists Removed' plugin removes the "(feat. ...)" from the _title_ field. it does not touch the "artist" field, so if there are featurings in the artist field, they will be left in.
- the 'Feat. Artists in Titles' plugin removes the "(feat. ...)" from the _artist_ and _albumartist_ field and adds them to the "title" string.

the last.fm plugin uses the _artist_ field to lookup tags from last.fm. so it will only find tags when the artist including the "(feat ...)" actually has tags on last.fm.

eg. "Major Lazer feat. Elliphant & Jovi Rockwell" simply has no tags: http://www.last.fm/music/Major+Lazer+feat.+Elliphant+&+Jovi+Rockwell ... therefore the track will get a lot of "Unknowns" (note that the "albumgenre" will have information, since it succeeded in finding last.fm tags from the albumartist or track 7, that has no featuring)

when you use the 'Feat. Artists in Titles' plugin, the "(feat. ...)" will be removed from the _artist_ fields and only "Major Lazer" will be left for the plugin to use: http://www.last.fm/music/Major+Lazer ... lots of tags.

i'll mark this as a feature request... maybe add removing of "(feat ...)" from the artist in case no tags are found for the artist with featuring, but for now you will have to move the featurings to the titles to fetch Major Lazer tags for all tracks...

**Comment by MarcusGHub** [comment]
I understand completely.

Adding it as feature would be great. Maybe just temporarily removing the "(feat. ...)" from artist to get the tags and adding it back.

I'll just do as you said and add the "(feat. ...)" to the title and then manually add it to artist after tagging it.

**Comment by MarcusGHub** [comment]
A quick question fdemmer, can MusicBrainz Picard read plugins from zip files?
I wanted to just clone you script and pull whenever there's an update.

**Comment by fdemmer** [comment]
@MarcusGHub no, but there is a picard issue open for that http://tickets.musicbrainz.org/browse/PICARD-750

if you are on linux (possibly macos) you can clone the plugin somewhere and symlink it to the plugin directory. that way you'd have the latest simply by pulling again.

**Comment by MarcusGHub** [comment]
I see.

I'm using Windows.

**Comment by fdemmer** [comment]
added in v0.11

**Comment by MarcusGHub** [comment]
Sorry to re-open, but still having the problem :(
Tested with v0.11, v0.12 and the master branch (which is now v0.12).

With the 'Feat. Artists in Titles' plugin enabled:
http://prntscr.com/8ten2k
http://prntscr.com/8tevi5

With the 'Feat. Artists Removed' plugin enabled:
http://prntscr.com/8teomf

With just 'Last.fm.ng' plugin enabled:
http://prntscr.com/8tepdn
http://prntscr.com/8terl3

Just have to continue with 'Feat. Artists in Titles' plugin enabled I guess.

**Comment by fdemmer** [comment]
did you enable `ignore_feat_artists` in your `config.ini`?

make sure you have this in the `[global]` section, is is **not** enabled by default:

```
[global]
ignore_feat_artists = True
```

with that there should be no need for using any of the other "feat" plugins for tagging.

it works for me:

![musicbrainz picard_025](https://cloud.githubusercontent.com/assets/630975/10621579/e5aad96a-7781-11e5-837c-5b29c584fff2.png)

if that does not work make sure your plugin install is clean. backup your `config.ini` and delete the plugin dir and all files. extract again from release zip and copy back the config.

check the log (help menu), there should be only one "W" (warning) line:

```
W: 23:34:38 Last.fm.ng - no tags: album, album=Do%20It%20Again&api_key=0a8b8f968b285654f9b4f16e8e33f2ee&method=album.gettoptags&artist=Pia%20Mia%20feat.%20Chris%20Brown%20%26%20Tyga
```

if there are three, there is something wrong.

**Comment by MarcusGHub** [comment]
Works perfectly!
THANK YOU!

I always look in the config file, but I overlooked that for some reason.
I made another change to the config. I added the separator ", " for my genres.
