### ISSUE TITLE
Last.fm.ng not grabbing tags. Server replied: Bad Request (QT code 302, HTTP code 400).

### ISSUE THREAD

**Issue by masud365** [fdemmer/Picard-Last.fm.ng-Plugin#56]
_[Worked earlier, but not working now. Don't know any reason. Showing many errors like Server replied: Bad Request (QT code 302, HTTP code 400).]_

#### Environment and versions

* Operating system:windows 10 version:1809 OS build:17763.437
* Picard version(s):2.1.3
* Plugin version(s) or commit hash:2.0.1

#### How to reproduce the problem

_[After first installing this plug-in worked just fine. Some days ago, all tag fields this plug-in has to fill is showing 'unknown'. Showing numerous error in debug field mostly, server replied: Bad Request (QT code 302, HTTP code 400). I have tried to reinstall the add-on including Picard. Cleans all Picard configuration files. Used different last.fm API key. For any Track or any album, no data grabbed from last.FM server. A track that tagged perfectly using this plug-in now showing all field unknown or some wrong value.]_
[last.fm.ng_error.txt](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/files/3070632/last.fm.ng_error.txt)
![picard_error](https://user-images.githubusercontent.com/49296952/55993530-df276580-5c9e-11e9-9633-53aebe89dfd1.png)

Sorry, for my bad English and thank you for this great extension.

**Comment by fdemmer** [comment]
thank you for the detailed report, your English is just fine :)

i reproduced the problem with this release: https://musicbrainz.org/release/e10adca8-31d4-4534-9ef9-f0f918e3e821

the problem is, that last.fm's api simply does not seem to know that album. you can see the response in the log or in a browser: https://ws.audioscrobbler.com/2.0/?method=album.gettoptags&album=Deutsche%20Schlager%201956%20-%201957&artist=Various%20Artists&api_key=0a8b8f968b285654f9b4f16e8e33f2ee

I found a matching album on last.fm, but it uses a different title: https://www.last.fm/music/Various+Artists/Deutsche+Schlager+(1956+-+1957)

there is nothing i can do about lastfm's api. naming of compilations is difficult and inconsistent.

however, besides the "album.gettoptags" request failing i see data being collected for some of the tracks (even though "Heavy Metal" seems wrong):

![MusicBrainzPicard_20190412_01](https://user-images.githubusercontent.com/630975/56023799-ff8f0880-5d0e-11e9-81a4-dbcd9b6b7d64.png)

so this is again an issue with last.fm. they simply have no tags for most of the songs.

sorry it's not a bug, just the data the apis provide, nothing i can do :(

i did change the logging of all those "AttributeErrors", because they are misleading and side effects of the "bad request" response from last.fm (d13528a185e9b5d2f326372c8458b755d392d801).

**Comment by masud365** [comment]
Thank you for the quick response, really appreciate your work. This album (Deutsche Schlager 1956 - 1957) gets all the correct tag information using this plugin and same version of Picard (look ‘Original Value’ information at screenshot).

![Deutsche Schlager 1956 - 1957 wrong tag](https://user-images.githubusercontent.com/49296952/56062437-e5c7e280-5d5b-11e9-99b5-5df57b637b5d.png)

 Now, I really don't understand what changed to not to work correctly. Not only this but also all other albums and song I throw in Picard get ‘wrong tag' or ‘unknown/no tag at all'.

![Citizen of Glass - wrong tag](https://user-images.githubusercontent.com/49296952/56062464-fa0bdf80-5d5b-11e9-9331-bbb70d0d5231.png)
![Any song any album - wrong tag](https://user-images.githubusercontent.com/49296952/56062513-29bae780-5d5c-11e9-92a9-19589eb7af57.png)
![List goes on](https://user-images.githubusercontent.com/49296952/56062523-317a8c00-5d5c-11e9-9273-220de7c177aa.png)
![Log for 'thank you next'](https://user-images.githubusercontent.com/49296952/56062532-39d2c700-5d5c-11e9-8cd6-4779c7d60a91.png)

[debug log.txt](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/files/3074960/debug.log.txt)

 Changing ‘last.fm' API doesn't have any effect. All screenshot here with your updated ‘python. py'. You may fix this problem at your spare time if you can recreate this issue.
 Again, thank you and sorry for bad English (if any :-) ).
